import type { MockEmail } from '../types.js';

export const MOCK_INBOX: MockEmail[] = [
  {
    id: 'em-asiana-conf',
    from: 'no-reply@flyasiana.com',
    to: 'steven@example.com',
    subject: 'Your Asiana booking is confirmed - XKRF2M',
    date: '2026-06-15T09:00:00Z',
    body: 'Confirmation XKRF2M. Flight OZ212 from Seoul Incheon (ICN) to San Francisco (SFO) on July 3, 2026. Passenger: Steven Yang.',
  },
  {
    id: 'em-asiana-club',
    from: 'club@flyasiana.com',
    to: 'steven@example.com',
    subject: 'Welcome to Asiana Club',
    date: '2024-02-10T09:00:00Z',
    body: 'Your Asiana Club membership number is 920384712. Earn miles on every flight.',
  },
  {
    id: 'em-amex',
    from: 'statements@americanexpress.com',
    to: 'steven@example.com',
    subject: 'Your American Express statement is ready',
    date: '2026-06-20T00:00:00Z',
    body: 'Card ending 1087. Recent charge: ASIANA AIRLINES $1,240.55 on Jun 15.',
  },
  {
    id: 'em-baggage',
    from: 'no-reply@flyasiana.com',
    to: 'steven@example.com',
    subject: 'Baggage receipt - OZ212',
    date: '2026-07-03T18:20:00Z',
    body: 'Checked baggage for flight OZ212. Baggage tag number 0988-7234. 1 checked bag to SFO.',
  },
  {
    id: 'em-arrival',
    from: 'no-reply@flyasiana.com',
    to: 'steven@example.com',
    subject: 'Thanks for flying Asiana - OZ212 has arrived',
    date: '2026-07-03T19:05:00Z',
    body: 'Your flight OZ212 (ICN to SFO) on July 3 has arrived. We hope you enjoyed your trip, Steven.',
  },
  {
    id: 'em-delta-old',
    from: 'noreply@delta.com',
    to: 'steven@example.com',
    subject: 'Delta itinerary DL55 - last year',
    date: '2025-03-02T00:00:00Z',
    body: 'Confirmation JKL999, Delta DL55 JFK->LAX. Unrelated old trip.',
  },
  {
    id: 'em-hotel',
    from: 'reservations@marriott.com',
    to: 'steven@example.com',
    subject: 'Your Marriott reservation in San Francisco',
    date: '2026-06-30T00:00:00Z',
    body: 'Reservation MAR777 for July 3-5. Not an airline booking.',
  },
  {
    id: 'em-promo-asiana',
    from: 'deals@flyasiana.com',
    to: 'steven@example.com',
    subject: 'Fall fare sale - save 25%',
    date: '2026-06-10T00:00:00Z',
    body: 'Promotional offer. No booking details.',
  },
  {
    id: 'em-amazon',
    from: 'ship-confirm@amazon.com',
    to: 'steven@example.com',
    subject: 'Your Amazon order has shipped',
    date: '2026-06-28T00:00:00Z',
    body: 'Order 111-222 shipped. Card ending 9999.',
  },
  { id: 'em-newsletter', from: 'news@thepointsguy.com', to: 'steven@example.com', subject: 'This week in points', date: '2026-07-01T00:00:00Z', body: 'Travel newsletter content.' },
  { id: 'em-uber', from: 'receipts@uber.com', to: 'steven@example.com', subject: 'Your trip receipt', date: '2026-07-03T20:00:00Z', body: 'Trip from SFO airport $52.10, card ending 1087.' },
  { id: 'em-united-old', from: 'noreply@united.com', to: 'steven@example.com', subject: 'United booking QWE111', date: '2024-11-01T00:00:00Z', body: 'Old United trip, unrelated.' },
  { id: 'em-work', from: 'boss@example.com', to: 'steven@example.com', subject: 'Re: Welcome back from Seoul', date: '2026-07-04T00:00:00Z', body: 'Glad you made it home. See you Monday.' },
  { id: 'em-checkin', from: 'no-reply@flyasiana.com', to: 'steven@example.com', subject: 'Check in for your flight OZ212', date: '2026-07-02T12:00:00Z', body: 'Check in now for OZ212 on July 3, confirmation XKRF2M.' },
  { id: 'em-amex-promo', from: 'offers@americanexpress.com', to: 'steven@example.com', subject: 'A new offer for you', date: '2026-06-05T00:00:00Z', body: 'Promotional. No statement details.' },
];

export const EXPECTED_DOSSIER = {
  pnr: 'XKRF2M',
  flight_number: 'OZ212',
  route: 'ICN -> SFO',
  loyalty_number: '920384712',
  payment_last4: '1087',
  baggage_tag: '0988-7234',
};
